// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public partial class DateFilial
{
    public int FilialId { get; set; }

    //public DateTime dateFrom { get; set; }
    //public DateTime dateTo { get; set; }
    public string dateFrom { get; set; }
    public string dateTo { get; set; }

}