// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public partial class Doljnost
{
    public int DoljId { get; set; }

    public string Name { get; set; }

    public string Primechanie { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }
}