// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Jurist.Models;

public partial class JuristContext : DbContext
{
    public JuristContext(DbContextOptions<JuristContext> options)
        : base(options)
    {
    }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Doljnost> Doljnosts { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Filial> Filials { get; set; }

    public virtual DbSet<LoginPassword> LoginPasswords { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<Predmet> Predmets { get; set; }

    public virtual DbSet<Pretense> Pretenses { get; set; }

    public virtual DbSet<PretenseDelete> PretenseDeletes { get; set; }

    public virtual DbSet<PretenseSumma> PretenseSummas { get; set; }

    public virtual DbSet<Result> Results { get; set; }

    public virtual DbSet<ResultSumma> ResultSummas { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<Summa> Summas { get; set; }

    public virtual DbSet<TablePretense> TablePretenses { get; set; }

    public virtual DbSet<Valutum> Valuta { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<City>(entity =>
        {
            entity.ToTable("City");

            entity.Property(e => e.CityId).HasColumnName("CityID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.ToTable("Country");

            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.NameFull)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Doljnost>(entity =>
        {
            entity.HasKey(e => e.DoljId);

            entity.ToTable("Doljnost");

            entity.Property(e => e.DoljId).HasColumnName("DoljID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmplId);

            entity.ToTable("Employee");

            entity.Property(e => e.EmplId).HasColumnName("EmplID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.DoljId).HasColumnName("DoljID");
            entity.Property(e => e.FilId).HasColumnName("FilID");
            entity.Property(e => e.FirstName)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.MiddleName)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.UserMod)
                .HasMaxLength(512)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Filial>(entity =>
        {
            entity.HasKey(e => e.FilId);

            entity.ToTable("Filial");

            entity.Property(e => e.FilId).HasColumnName("FilID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.NameFull)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie1)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie2)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie3)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<LoginPassword>(entity =>
        {
            entity.ToTable("LoginPassword");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.EmplId).HasColumnName("EmplID");
            entity.Property(e => e.Login)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.ThemeColor)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(e => e.OrgId);

            entity.ToTable("Organization");

            entity.Property(e => e.OrgId).HasColumnName("OrgID");
            entity.Property(e => e.Address)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.CityId).HasColumnName("CityID");
            entity.Property(e => e.CounrtyId).HasColumnName("CounrtyID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie1)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie2)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie3)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Unp)
                .HasMaxLength(64)
                .IsUnicode(false)
                .HasColumnName("UNP");
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Predmet>(entity =>
        {
            entity.ToTable("Predmet");

            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.Predmet1)
                .HasMaxLength(512)
                .IsUnicode(false)
                .HasColumnName("Predmet");
            entity.Property(e => e.Primechanie1)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie2)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie3)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Pretense>(entity =>
        {
            entity.HasKey(e => e.PretId);

            entity.ToTable("Pretense");

            entity.Property(e => e.PretId).HasColumnName("PretID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.DatePret).HasColumnType("datetime");
            entity.Property(e => e.DateRassmPret).HasColumnType("datetime");
            entity.Property(e => e.FilId).HasColumnName("FilID");
            entity.Property(e => e.Inout).HasColumnName("inout");
            entity.Property(e => e.NumberPret)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.OrgId).HasColumnName("OrgID");
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.SummaDolg).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SummaPeny).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SummaPoshlina).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SummaProc).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.ValId).HasColumnName("ValID");
        });

        modelBuilder.Entity<PretenseDelete>(entity =>
        {
            entity.HasKey(e => e.PretDelId);

            entity.ToTable("PretenseDelete");

            entity.Property(e => e.PretDelId).HasColumnName("PretDelID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.DatePret).HasColumnType("datetime");
            entity.Property(e => e.DateRassmPret).HasColumnType("datetime");
            entity.Property(e => e.FilId).HasColumnName("FilID");
            entity.Property(e => e.Inout).HasColumnName("inout");
            entity.Property(e => e.NumberPret)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.OrgId).HasColumnName("OrgID");
            entity.Property(e => e.PretId).HasColumnName("PretID");
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.SummaDolg).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SummaPeny).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SummaProc).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.ValId).HasColumnName("ValID");
        });

        modelBuilder.Entity<PretenseSumma>(entity =>
        {
            entity.HasKey(e => e.PretSummId);

            entity.ToTable("PretenseSumma");

            entity.Property(e => e.PretSummId).HasColumnName("PretSummID");
            entity.Property(e => e.PretId).HasColumnName("PretID");
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.SummaId).HasColumnName("SummaID");
            entity.Property(e => e.ValId).HasColumnName("ValID");
            entity.Property(e => e.Value).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<Result>(entity =>
        {
            entity.HasKey(e => e.ResId);

            entity.ToTable("Result");

            entity.Property(e => e.ResId).HasColumnName("ResID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.Primechanie1)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie2)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie3)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Result1)
                .HasMaxLength(2048)
                .IsUnicode(false)
                .HasColumnName("Result");
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ResultSumma>(entity =>
        {
            entity.HasKey(e => e.ResSummaId);

            entity.ToTable("ResultSumma");

            entity.Property(e => e.ResSummaId).HasColumnName("ResSummaID");
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.ResultId).HasColumnName("ResultID");
            entity.Property(e => e.SummaId).HasColumnName("SummaID");
            entity.Property(e => e.ValId).HasColumnName("ValID");
            entity.Property(e => e.Value).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.ToTable("Status");

            entity.Property(e => e.StatusId).HasColumnName("StatusID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Summa>(entity =>
        {
            entity.ToTable("Summa");

            entity.Property(e => e.SummaId).HasColumnName("SummaID");
            entity.Property(e => e.Name)
                .HasMaxLength(256)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TablePretense>(entity =>
        {
            entity.HasKey(e => e.TabPretId);

            entity.ToTable("TablePretense");

            entity.Property(e => e.TabPretId).HasColumnName("TabPretID");
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.DateTabPret).HasColumnType("datetime");
            entity.Property(e => e.PretId).HasColumnName("PretID");
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.Result)
                .HasMaxLength(2048)
                .IsUnicode(false);
            entity.Property(e => e.StatusId).HasColumnName("StatusID");
            entity.Property(e => e.SummaDolg).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SummaPeny).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SummaPoshlina).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SummaProc).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.ValId).HasColumnName("ValID");
        });

        modelBuilder.Entity<Valutum>(entity =>
        {
            entity.HasKey(e => e.ValId);

            entity.Property(e => e.ValId).HasColumnName("ValID");
            entity.Property(e => e.CodeVal)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.DateMod).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(128)
                .IsUnicode(false);
            entity.Property(e => e.NameFull)
                .HasMaxLength(256)
                .IsUnicode(false);
            entity.Property(e => e.Primechanie)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.UserMod)
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}