// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Jurist.Models;
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public partial class LoginModel
{
    public int Id { get; set; }

    public string Login1 { get; set; }

    public string Password { get; set; }

    public string LastName { get; set; }
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string fio { get; set; }

    public int? FilialId { get; set; }
    public string FilialName { get; set; }

    public int? Admin { get; set; }
    public string ThemeColor { get; set; }
    public string token { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }

    public string Primechanie { get; set; }

    public virtual Filial Filial { get; set; }
}