// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public partial class LoginPassword
{
    public int Id { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public int? EmplId { get; set; }

    public int? Admin { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }

    public string ThemeColor { get; set; }
}