// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Jurist.Models;
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public class NbrbValuta
{
    public int Cur_ID { get; set; }
    public string Cur_Abbreviation { get; set; }
    public string Cur_Name { get; set; }
    public int Cur_Scale { get; set; }
    public decimal Cur_OfficialRate { get; set; }
}