// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public partial class Predmet
{
    public int PredmetId { get; set; }

    public string Predmet1 { get; set; }

    public string Primechanie1 { get; set; }

    public string Primechanie2 { get; set; }

    public string Primechanie3 { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }
}