// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public partial class Pretense
{
    public int PretId { get; set; }

    public int? OrgId { get; set; }

    public string NumberPret { get; set; }

    public DateTime? DatePret { get; set; }

    public decimal? SummaDolg { get; set; }

    public decimal? SummaPeny { get; set; }

    public decimal? SummaProc { get; set; }

    public int? ValId { get; set; }

    public DateTime? DateRassmPret { get; set; }

    public string Primechanie { get; set; }

    public int? Visible { get; set; }

    public int? FilId { get; set; }

    public int? Inout { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }

    public int? Arhiv { get; set; }

    public int? PredmetId { get; set; }

    public decimal? SummaPoshlina { get; set; }
}