// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public partial class ResultSumma
{
    public int ResSummaId { get; set; }

    public int ResultId { get; set; }

    public int SummaId { get; set; }

    public int ValId { get; set; }

    public decimal? Value { get; set; }

    public string Primechanie { get; set; }
}