// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public partial class Summa
{
    public int SummaId { get; set; }

    public string Name { get; set; }

    public string Primechanie { get; set; }
}