// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jurist.Models;

public partial class TablePretense
{
    public int TabPretId { get; set; }

    public int? PretId { get; set; }

    public DateTime? DateTabPret { get; set; }

    public decimal? SummaDolg { get; set; }

    public decimal? SummaPeny { get; set; }

    public decimal? SummaProc { get; set; }

    public int? ValId { get; set; }

    public string Result { get; set; }

    public string Primechanie { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }

    public int? StatusId { get; set; }

    public int? Delet { get; set; }

    public decimal? SummaPoshlina { get; set; }
   
}